on:
  workflow_call:

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel babel
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

          if grep -q "compile_catalog" setup.cfg
          then
            python setup.py compile_catalog
          fi
      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
